#!/bin/sh
set -eu

LINE_COUNT="$1"
INPUT_FILE="$2"
OUTPUT_FILE_HEAD="$3"
OUTPUT_FILE_TAIL="$4"

head -n "$LINE_COUNT" < "$INPUT_FILE" > "$OUTPUT_FILE_HEAD"
tail -n "+$((1+$LINE_COUNT))" < "$INPUT_FILE" > "$OUTPUT_FILE_TAIL"
